version: '3.8'

services:
  api-users:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=apiusers